version: '3'

services:
    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginx
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8901:8901"
            - "8902:8902"
            - "8903:8903"
            - "8904:8904"
            - "8905:8905"
    meta1:
        image: cnosdb/cnosdb:meta-latest
        container_name: meta1.cnosdb.com
        volumes:
            - ./conf/meta1:/etc/cnosdb
    meta2:
        image: cnosdb/cnosdb:meta-latest
        container_name: meta2.cnosdb.com
        volumes:
            - ./conf/meta2:/etc/cnosdb
    meta3:
        image: cnosdb/cnosdb:meta-latest
        container_name: meta3.cnosdb.com
        volumes:
            - ./conf/meta3:/etc/cnosdb
    script-runner:
        image: ubuntu:latest
        container_name: script-runner
        volumes:
            - ./scripts/meta_init.sh:/scripts/meta_init.sh
        command:
            - /bin/bash
            - -c
            - |
                apt update && apt install -y curl jq netcat
                chmod +x /scripts/meta_init.sh
                /scripts/meta_init.sh
        healthcheck:
            test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 50
    query_tskv1:
        image: cnosdb/cnosdb:latest
        container_name: query_tskv1.cnosdb.com
        volumes:
            - ./conf/query_tskv1:/etc/cnosdb
        depends_on:
            script-runner:
                condition: service_healthy
#    query_tskv2:
#        image: cnosdb/cnosdb:latest
#        container_name: query_tskv2.cnosdb.com
#        volumes:
#            - ./conf/query_tskv2:/etc/cnosdb
